NAME := banyand
SERVER := $(NAME)-server
BINARIES := $(SERVER)
DEBUG_BINARIES := $(SERVER)-debug

include ../scripts/build/build.mk
include ../scripts/build/test.mk
include ../scripts/build/lint.mk
include ../scripts/build/help.mk
