// Licensed to Apache Software Foundation (ASF) under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Apache Software Foundation (ASF) licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Command fixturegen writes the checked-in legacy ICE v3 corpus that the
// pkg/index/inverted contract tests read. It is the independent oracle for
// those tests: the bytes come from the pinned legacy writer, never from the
// native reader under test.
//
// The generated directory holds one committed segment carrying the logical
// documents doc-11 and doc-12, no deletion record, and arbitrary non-zero
// bytes in every reserved CRC32 field. Alongside it the command writes a
// provenance manifest recording the oracle module versions, this command line,
// the logical documents, the SHA-256 of every generated file and the declared
// visible document count.
//
// Regenerate with:
//
//	go run ./pkg/index/inverted/internal/icev3/fixturegen \
//	  -out pkg/index/inverted/testdata/icev3/single-segment
//
// The legacy writer does not emit byte-identical output across runs (a
// manifest records the segment's in-memory size estimate, which varies), so a
// regenerated corpus is a NEW corpus: commit the refreshed bytes and the
// refreshed manifest together.
//
// No production code path reaches this command. It is the only place in the
// repository that drives the legacy writer to produce fixture bytes.
package main

import (
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"runtime/debug"
	"sort"
	"time"

	"github.com/blugelabs/bluge"
)

const (
	// indexDirName holds the corpus exactly as the legacy writer left it. The
	// provenance manifest sits beside it rather than inside it so that the
	// contract test can assert the corpus directory is byte-for-byte what the
	// oracle produced.
	indexDirName    = "index"
	manifestName    = "provenance.json"
	lockFilename    = "bluge.pid"
	segmentFooterLn = 60
	crcWidth        = 4
	// expectedVisibleCount is the declared visible document count for this
	// corpus, taken from the milestone specification rather than from the
	// generated bytes. Generation fails if the oracle disagrees with it.
	expectedVisibleCount = 2
	// reservedCRCFill is the arbitrary non-zero value written over every
	// reserved CRC32 field, so a reader that validates one cannot pass.
	reservedCRCFill uint32 = 0xDEADBEEF
)

// logicalDocuments are the document identities the corpus contains, in the
// order the oracle indexes them.
var logicalDocuments = []string{"doc-11", "doc-12"}

// manifest is the provenance record checked in beside the corpus.
type manifest struct {
	Oracle               map[string]string  `json:"oracle_versions"`
	FileSHA256           map[string]string  `json:"file_sha256"`
	GeneratorCommand     string             `json:"generator_command"`
	Description          string             `json:"description"`
	LogicalDocuments     []string           `json:"logical_documents"`
	SnapshotGenerations  []snapshotRecord   `json:"snapshot_generations"`
	SegmentFooters       []segmentFooterRec `json:"segment_footers"`
	ExpectedVisibleCount int64              `json:"expected_visible_count"`
	DeletionRecords      int                `json:"deletion_records"`
	ReservedCRC32Patched bool               `json:"reserved_crc32_patched"`
}

// snapshotRecord describes one `.snp` generation of the corpus.
type snapshotRecord struct {
	File                  string `json:"file"`
	Version               uint64 `json:"version"`
	SegmentCount          uint64 `json:"segment_count"`
	DeclaredVisibleCount  int64  `json:"declared_visible_count"`
	DeletionBitmapEntries uint64 `json:"deletion_bitmap_entries"`
}

// segmentFooterRec describes the decoded 60-byte footer of one `.seg` file.
type segmentFooterRec struct {
	File              string `json:"file"`
	NumDocs           uint64 `json:"num_docs"`
	StoredIndexOffset uint64 `json:"stored_index_offset"`
	FieldsIndexOffset uint64 `json:"fields_index_offset"`
	DocValueOffset    uint64 `json:"doc_value_offset"`
	ChunkMode         uint32 `json:"chunk_mode"`
	Version           uint32 `json:"version"`
	SizeBytes         int64  `json:"size_bytes"`
}

func main() {
	out := flag.String("out", "pkg/index/inverted/testdata/icev3/single-segment", "directory that receives the corpus and its provenance manifest")
	flag.Parse()
	if err := generate(*out); err != nil {
		fmt.Fprintf(os.Stderr, "fixturegen: %v\n", err)
		os.Exit(1)
	}
}

// generate writes the corpus and its provenance manifest under root.
func generate(root string) error {
	indexDir := filepath.Join(root, indexDirName)
	if err := os.RemoveAll(root); err != nil {
		return fmt.Errorf("failed to clear %s: %w", root, err)
	}
	if err := os.MkdirAll(indexDir, 0o750); err != nil {
		return fmt.Errorf("failed to create %s: %w", indexDir, err)
	}
	if err := writeCorpus(indexDir); err != nil {
		return err
	}
	if err := patchReservedCRC32(indexDir); err != nil {
		return err
	}
	m, err := describe(indexDir, root)
	if err != nil {
		return err
	}
	body, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to encode manifest: %w", err)
	}
	body = append(body, '\n')
	if err = os.WriteFile(filepath.Join(root, manifestName), body, 0o600); err != nil {
		return fmt.Errorf("failed to write manifest: %w", err)
	}
	fmt.Printf("wrote %s (%d logical documents, declared visible count %d)\n", root, len(logicalDocuments), expectedVisibleCount)
	return nil
}

// writeCorpus drives the pinned legacy writer to commit the logical documents
// into indexDir and returns once the writer has released the directory.
func writeCorpus(indexDir string) error {
	writer, err := bluge.OpenWriter(bluge.DefaultConfig(indexDir))
	if err != nil {
		return fmt.Errorf("failed to open the legacy writer on %s: %w", indexDir, err)
	}
	batch := bluge.NewBatch()
	for _, docID := range logicalDocuments {
		doc := bluge.NewDocument(docID)
		doc.AddField(bluge.NewKeywordField("_series_id", "nidx-01a").StoreValue())
		batch.Insert(doc)
	}
	if err = writer.Batch(batch); err != nil {
		_ = writer.Close()
		return fmt.Errorf("failed to index the batch: %w", err)
	}
	if err = waitForCommittedGeneration(indexDir); err != nil {
		_ = writer.Close()
		return err
	}
	if err = writer.Close(); err != nil {
		return fmt.Errorf("failed to close the legacy writer: %w", err)
	}
	if _, err = os.Stat(filepath.Join(indexDir, lockFilename)); err == nil {
		return fmt.Errorf("the legacy writer left %s behind; the corpus must never carry the writer lock", lockFilename)
	}
	return nil
}

// waitForCommittedGeneration blocks until the legacy writer has published at
// least one snapshot manifest and one segment file.
func waitForCommittedGeneration(indexDir string) error {
	deadline := time.Now().Add(30 * time.Second)
	for time.Now().Before(deadline) {
		snapshots, err := filepath.Glob(filepath.Join(indexDir, "*.snp"))
		if err != nil {
			return fmt.Errorf("failed to enumerate manifests: %w", err)
		}
		segments, err := filepath.Glob(filepath.Join(indexDir, "*.seg"))
		if err != nil {
			return fmt.Errorf("failed to enumerate segments: %w", err)
		}
		if len(snapshots) > 0 && len(segments) > 0 {
			return nil
		}
		time.Sleep(50 * time.Millisecond)
	}
	return fmt.Errorf("the legacy writer published no committed generation in %s", indexDir)
}

// patchReservedCRC32 overwrites the reserved CRC32 field of every generated
// file with arbitrary non-zero bytes.
func patchReservedCRC32(indexDir string) error {
	paths, err := corpusFiles(indexDir)
	if err != nil {
		return err
	}
	for _, path := range paths {
		body, readErr := os.ReadFile(path) //nolint:gosec // fixture path assembled from the -out flag.
		if readErr != nil {
			return fmt.Errorf("failed to read %s: %w", path, readErr)
		}
		if len(body) < crcWidth {
			return fmt.Errorf("%s is shorter than its reserved CRC32 field", path)
		}
		binary.BigEndian.PutUint32(body[len(body)-crcWidth:], reservedCRCFill)
		if writeErr := os.WriteFile(path, body, 0o600); writeErr != nil {
			return fmt.Errorf("failed to rewrite %s: %w", path, writeErr)
		}
	}
	return nil
}

// corpusFiles returns the sorted paths of every file in the corpus directory.
func corpusFiles(indexDir string) ([]string, error) {
	entries, err := os.ReadDir(indexDir)
	if err != nil {
		return nil, fmt.Errorf("failed to read %s: %w", indexDir, err)
	}
	var paths []string
	for _, entry := range entries {
		if entry.IsDir() {
			return nil, fmt.Errorf("unexpected directory %s inside the corpus", entry.Name())
		}
		paths = append(paths, filepath.Join(indexDir, entry.Name()))
	}
	sort.Strings(paths)
	return paths, nil
}

// describe decodes the generated corpus and returns its provenance manifest,
// failing if the oracle disagrees with the declared visible count.
func describe(indexDir, root string) (*manifest, error) {
	paths, err := corpusFiles(indexDir)
	if err != nil {
		return nil, err
	}
	m := &manifest{
		Description: "Legacy-writer ICE v3 / snapshot v3 corpus for NIDX-01A: one committed segment, " +
			"documents doc-11 and doc-12, no deletion record, arbitrary non-zero reserved CRC32 bytes.",
		GeneratorCommand:     fmt.Sprintf("go run ./pkg/index/inverted/internal/icev3/fixturegen -out %s", root),
		Oracle:               oracleVersions(),
		LogicalDocuments:     logicalDocuments,
		ExpectedVisibleCount: expectedVisibleCount,
		ReservedCRC32Patched: true,
		FileSHA256:           map[string]string{},
	}
	for _, path := range paths {
		body, readErr := os.ReadFile(path) //nolint:gosec // fixture path assembled from the -out flag.
		if readErr != nil {
			return nil, fmt.Errorf("failed to read %s: %w", path, readErr)
		}
		sum := sha256.Sum256(body)
		name := filepath.Base(path)
		m.FileSHA256[name] = hex.EncodeToString(sum[:])
		switch filepath.Ext(name) {
		case ".seg":
			footer, footerErr := decodeSegmentFooter(name, body)
			if footerErr != nil {
				return nil, footerErr
			}
			m.SegmentFooters = append(m.SegmentFooters, *footer)
		case ".snp":
			record, recordErr := decodeSnapshot(name, body)
			if recordErr != nil {
				return nil, recordErr
			}
			m.SnapshotGenerations = append(m.SnapshotGenerations, *record)
		default:
			return nil, fmt.Errorf("unexpected file %s in the corpus", name)
		}
	}
	return m, validate(m)
}

// validate rejects a corpus that does not match the shape NIDX-01A declares.
func validate(m *manifest) error {
	if len(m.SegmentFooters) != 1 {
		return fmt.Errorf("expected exactly one committed segment, found %d", len(m.SegmentFooters))
	}
	if got := m.SegmentFooters[0].NumDocs; got != expectedVisibleCount {
		return fmt.Errorf("segment footer declares %d documents, expected %d", got, expectedVisibleCount)
	}
	if len(m.SnapshotGenerations) == 0 {
		return fmt.Errorf("the corpus carries no snapshot generation")
	}
	for _, generation := range m.SnapshotGenerations {
		if generation.Version != 3 {
			return fmt.Errorf("%s is snapshot version %d, expected 3", generation.File, generation.Version)
		}
		if generation.SegmentCount != 1 {
			return fmt.Errorf("%s references %d segments, expected 1", generation.File, generation.SegmentCount)
		}
		if generation.DeclaredVisibleCount != expectedVisibleCount {
			return fmt.Errorf("%s declares %d visible documents, expected %d",
				generation.File, generation.DeclaredVisibleCount, expectedVisibleCount)
		}
		if generation.DeletionBitmapEntries != 0 {
			return fmt.Errorf("%s carries a deletion record, which this corpus must not", generation.File)
		}
	}
	return nil
}

// decodeSegmentFooter reads the fixed 60-byte big-endian footer at the end of
// an ICE v3 segment file.
func decodeSegmentFooter(name string, body []byte) (*segmentFooterRec, error) {
	if len(body) < segmentFooterLn {
		return nil, fmt.Errorf("%s is %d bytes, shorter than the %d-byte footer", name, len(body), segmentFooterLn)
	}
	f := body[len(body)-segmentFooterLn:]
	return &segmentFooterRec{
		File:              name,
		NumDocs:           binary.BigEndian.Uint64(f[0:8]),
		StoredIndexOffset: binary.BigEndian.Uint64(f[8:16]),
		FieldsIndexOffset: binary.BigEndian.Uint64(f[16:24]),
		DocValueOffset:    binary.BigEndian.Uint64(f[24:32]),
		ChunkMode:         binary.BigEndian.Uint32(f[32:36]),
		Version:           binary.BigEndian.Uint32(f[52:56]),
		SizeBytes:         int64(len(body)),
	}, nil
}

// decodeSnapshot reads a snapshot v3 manifest far enough to record the
// generation's shape: its version, its segment count, the visible document
// count it declares and whether it carries a deletion record.
func decodeSnapshot(name string, body []byte) (*snapshotRecord, error) {
	r := &cursor{body: body}
	version := r.uvarint()
	segmentCount := r.uvarint()
	record := &snapshotRecord{File: name, Version: version, SegmentCount: segmentCount}
	for i := uint64(0); i < segmentCount; i++ {
		typeLen := r.uvarint()
		r.skip(int(typeLen))
		r.skip(4) // segment version
		r.uvarint()
		r.skip(8) // in-memory size estimate; deliberately not a file size
		record.DeclaredVisibleCount += int64(r.uint64())
		r.skip(16) // time bounds
		deletionLen := r.uvarint()
		record.DeletionBitmapEntries += deletionLen
		r.skip(int(deletionLen))
	}
	if r.err != nil {
		return nil, fmt.Errorf("failed to decode %s: %w", name, r.err)
	}
	if remaining := len(body) - r.at; remaining != crcWidth {
		return nil, fmt.Errorf("%s has %d trailing bytes after its records, expected the %d-byte reserved CRC32", name, remaining, crcWidth)
	}
	return record, nil
}

// cursor walks a snapshot manifest, latching the first decode failure.
type cursor struct {
	err  error
	body []byte
	at   int
}

// uvarint consumes one unsigned LEB128 value.
func (c *cursor) uvarint() uint64 {
	if c.err != nil {
		return 0
	}
	value, read := binary.Uvarint(c.body[c.at:])
	if read <= 0 {
		c.err = fmt.Errorf("malformed uvarint at offset %d", c.at)
		return 0
	}
	c.at += read
	return value
}

// uint64 consumes one big-endian fixed-width unsigned 64-bit value.
func (c *cursor) uint64() uint64 {
	if c.err != nil || c.at+8 > len(c.body) {
		c.err = fmt.Errorf("truncated uint64 at offset %d", c.at)
		return 0
	}
	value := binary.BigEndian.Uint64(c.body[c.at : c.at+8])
	c.at += 8
	return value
}

// skip advances over n bytes.
func (c *cursor) skip(n int) {
	if c.err != nil {
		return
	}
	if n < 0 || c.at+n > len(c.body) {
		c.err = fmt.Errorf("cannot skip %d bytes at offset %d", n, c.at)
		return
	}
	c.at += n
}

// oracleVersions reports the pinned module versions that produced the corpus.
func oracleVersions() map[string]string {
	versions := map[string]string{}
	info, ok := debug.ReadBuildInfo()
	if !ok {
		return versions
	}
	for _, dep := range info.Deps {
		switch dep.Path {
		case "github.com/blugelabs/bluge", "github.com/blugelabs/ice", "github.com/RoaringBitmap/roaring":
			effective := dep
			if dep.Replace != nil {
				effective = dep.Replace
			}
			versions[dep.Path] = effective.Path + "@" + effective.Version
		}
	}
	return versions
}
