// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64 && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfGlobalStats struct {
	MinorFaults  uint64
	MajorFaults  uint64
	PageAccesses uint64
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	HandleMmFault       *ebpf.ProgramSpec `ebpf:"handle_mm_fault"`
	MarkPageAccessed    *ebpf.ProgramSpec `ebpf:"mark_page_accessed"`
	TracepointEnterRead *ebpf.ProgramSpec `ebpf:"tracepoint_enter_read"`
	TracepointExitRead  *ebpf.ProgramSpec `ebpf:"tracepoint_exit_read"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	GlobalStatsMap *ebpf.MapSpec `ebpf:"global_stats_map"`
	MonitorFd      *ebpf.MapSpec `ebpf:"monitor_fd"`
	ReadFdCache    *ebpf.MapSpec `ebpf:"read_fd_cache"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	GlobalStatsMap *ebpf.Map `ebpf:"global_stats_map"`
	MonitorFd      *ebpf.Map `ebpf:"monitor_fd"`
	ReadFdCache    *ebpf.Map `ebpf:"read_fd_cache"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.GlobalStatsMap,
		m.MonitorFd,
		m.ReadFdCache,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	HandleMmFault       *ebpf.Program `ebpf:"handle_mm_fault"`
	MarkPageAccessed    *ebpf.Program `ebpf:"mark_page_accessed"`
	TracepointEnterRead *ebpf.Program `ebpf:"tracepoint_enter_read"`
	TracepointExitRead  *ebpf.Program `ebpf:"tracepoint_exit_read"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.HandleMmFault,
		p.MarkPageAccessed,
		p.TracepointEnterRead,
		p.TracepointExitRead,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_arm64_bpfel.o
var _BpfBytes []byte