# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: banyandb/model/v1/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'banyandb/model/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x62\x61nyandb/model/v1/common.proto\x12\x11\x62\x61nyandb.model.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x14\n\x03Str\x12\r\n\x05value\x18\x01 \x01(\t\"\x14\n\x03Int\x12\r\n\x05value\x18\x01 \x01(\x03\"\x16\n\x05\x46loat\x12\r\n\x05value\x18\x01 \x01(\x01\"\x19\n\x08StrArray\x12\r\n\x05value\x18\x01 \x03(\t\"\x19\n\x08IntArray\x12\r\n\x05value\x18\x01 \x03(\x03\"\xb9\x02\n\x08TagValue\x12*\n\x04null\x18\x01 \x01(\x0e\x32\x1a.google.protobuf.NullValueH\x00\x12%\n\x03str\x18\x02 \x01(\x0b\x32\x16.banyandb.model.v1.StrH\x00\x12\x30\n\tstr_array\x18\x03 \x01(\x0b\x32\x1b.banyandb.model.v1.StrArrayH\x00\x12%\n\x03int\x18\x04 \x01(\x0b\x32\x16.banyandb.model.v1.IntH\x00\x12\x30\n\tint_array\x18\x05 \x01(\x0b\x32\x1b.banyandb.model.v1.IntArrayH\x00\x12\x15\n\x0b\x62inary_data\x18\x06 \x01(\x0cH\x00\x12/\n\ttimestamp\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00\x42\x07\n\x05value\">\n\x11TagFamilyForWrite\x12)\n\x04tags\x18\x01 \x03(\x0b\x32\x1b.banyandb.model.v1.TagValue\"\xd1\x01\n\nFieldValue\x12*\n\x04null\x18\x01 \x01(\x0e\x32\x1a.google.protobuf.NullValueH\x00\x12%\n\x03str\x18\x02 \x01(\x0b\x32\x16.banyandb.model.v1.StrH\x00\x12%\n\x03int\x18\x03 \x01(\x0b\x32\x16.banyandb.model.v1.IntH\x00\x12\x15\n\x0b\x62inary_data\x18\x04 \x01(\x0cH\x00\x12)\n\x05\x66loat\x18\x05 \x01(\x0b\x32\x18.banyandb.model.v1.FloatH\x00\x42\x07\n\x05value*\xd4\x01\n\x13\x41ggregationFunction\x12$\n AGGREGATION_FUNCTION_UNSPECIFIED\x10\x00\x12\x1d\n\x19\x41GGREGATION_FUNCTION_MEAN\x10\x01\x12\x1c\n\x18\x41GGREGATION_FUNCTION_MAX\x10\x02\x12\x1c\n\x18\x41GGREGATION_FUNCTION_MIN\x10\x03\x12\x1e\n\x1a\x41GGREGATION_FUNCTION_COUNT\x10\x04\x12\x1c\n\x18\x41GGREGATION_FUNCTION_SUM\x10\x05\x42l\n\'org.apache.skywalking.banyandb.model.v1ZAgithub.com/apache/skywalking-banyandb/api/proto/banyandb/model/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'banyandb.model.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\'org.apache.skywalking.banyandb.model.v1ZAgithub.com/apache/skywalking-banyandb/api/proto/banyandb/model/v1'
  _globals['_AGGREGATIONFUNCTION']._serialized_start=831
  _globals['_AGGREGATIONFUNCTION']._serialized_end=1043
  _globals['_STR']._serialized_start=116
  _globals['_STR']._serialized_end=136
  _globals['_INT']._serialized_start=138
  _globals['_INT']._serialized_end=158
  _globals['_FLOAT']._serialized_start=160
  _globals['_FLOAT']._serialized_end=182
  _globals['_STRARRAY']._serialized_start=184
  _globals['_STRARRAY']._serialized_end=209
  _globals['_INTARRAY']._serialized_start=211
  _globals['_INTARRAY']._serialized_end=236
  _globals['_TAGVALUE']._serialized_start=239
  _globals['_TAGVALUE']._serialized_end=552
  _globals['_TAGFAMILYFORWRITE']._serialized_start=554
  _globals['_TAGFAMILYFORWRITE']._serialized_end=616
  _globals['_FIELDVALUE']._serialized_start=619
  _globals['_FIELDVALUE']._serialized_end=828
# @@protoc_insertion_point(module_scope)
