# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'Setup Build Environment'
description: 'Common setup steps for BanyanDB builds'

inputs:
  download-artifacts:
    description: 'Whether to download build artifacts'
    required: false
    default: 'true'
  setup-docker:
    description: 'Whether to setup Docker Buildx'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Download build artifacts
      if: inputs.download-artifacts == 'true'
      uses: actions/download-artifact@v7
      with:
        name: build-artifacts

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24.6.0
        cache: 'npm'
        cache-dependency-path: |
          ui/package-lock.json
          mcp/package-lock.json

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache: true

    - name: Setup kind
      uses: helm/kind-action@92086f6be054225fa813e0a4b13787fc9088faab # v1.13.0
      with:
        version: v0.30.0
        install_only: true

    - name: Set up Docker Buildx
      if: inputs.setup-docker == 'true'
      uses: docker/setup-buildx-action@v1
