// Code generated by mockery (devel). DO NOT EDIT.

package mocks

import (
	types "github.com/apache/skywalking-banyandb/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// Field is an autogenerated mock type for the Field type
type Field struct {
	mock.Mock
}

// Name provides a mock function with given fields:
func (_m *Field) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Type provides a mock function with given fields:
func (_m *Field) Type() types.FieldType {
	ret := _m.Called()

	var r0 types.FieldType
	if rf, ok := ret.Get(0).(func() types.FieldType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(types.FieldType)
	}

	return r0
}
