// Code generated by mockery (devel). DO NOT EDIT.

package mocks

import (
	types "github.com/apache/skywalking-banyandb/pkg/types"
	mock "github.com/stretchr/testify/mock"
)

// Schema is an autogenerated mock type for the Schema type
type Schema struct {
	mock.Mock
}

// GetFields provides a mock function with given fields:
func (_m *Schema) GetFields() []types.Field {
	ret := _m.Called()

	var r0 []types.Field
	if rf, ok := ret.Get(0).(func() []types.Field); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Field)
		}
	}

	return r0
}

// Select provides a mock function with given fields: names
func (_m *Schema) Select(names ...string) types.Schema {
	_va := make([]interface{}, len(names))
	for _i := range names {
		_va[_i] = names[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 types.Schema
	if rf, ok := ret.Get(0).(func(...string) types.Schema); ok {
		r0 = rf(names...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Schema)
		}
	}

	return r0
}
