# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: banyandb/measure/v1/write.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'banyandb/measure/v1/write.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from banyandb.common.v1 import common_pb2 as banyandb_dot_common_dot_v1_dot_common__pb2
from banyandb.model.v1 import common_pb2 as banyandb_dot_model_dot_v1_dot_common__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x62\x61nyandb/measure/v1/write.proto\x12\x13\x62\x61nyandb.measure.v1\x1a\x1f\x62\x61nyandb/common/v1/common.proto\x1a\x1e\x62\x61nyandb/model/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"\xcf\x01\n\x0e\x44\x61taPointValue\x12\x37\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x08\xfa\x42\x05\x8a\x01\x02\x08\x01\x12\x44\n\x0ctag_families\x18\x02 \x03(\x0b\x32$.banyandb.model.v1.TagFamilyForWriteB\x08\xfa\x42\x05\x92\x01\x02\x08\x01\x12-\n\x06\x66ields\x18\x03 \x03(\x0b\x32\x1d.banyandb.model.v1.FieldValue\x12\x0f\n\x07version\x18\x04 \x01(\x03\"\xa7\x01\n\x0cWriteRequest\x12\x38\n\x08metadata\x18\x01 \x01(\x0b\x32\x1c.banyandb.common.v1.MetadataB\x08\xfa\x42\x05\xba\x01\x02\x08\x01\x12\x41\n\ndata_point\x18\x02 \x01(\x0b\x32#.banyandb.measure.v1.DataPointValueB\x08\xfa\x42\x05\xba\x01\x02\x08\x01\x12\x1a\n\nmessage_id\x18\x03 \x01(\x04\x42\x06\xfa\x42\x03\x9a\x01\x00\"k\n\rWriteResponse\x12\x1a\n\nmessage_id\x18\x01 \x01(\x04\x42\x06\xfa\x42\x03\x9a\x01\x00\x12\x0e\n\x06status\x18\x02 \x01(\t\x12.\n\x08metadata\x18\x03 \x01(\x0b\x32\x1c.banyandb.common.v1.Metadata\"\x90\x01\n\x14InternalWriteRequest\x12\x10\n\x08shard_id\x18\x01 \x01(\r\x12\x32\n\rentity_values\x18\x02 \x03(\x0b\x32\x1b.banyandb.model.v1.TagValue\x12\x32\n\x07request\x18\x03 \x01(\x0b\x32!.banyandb.measure.v1.WriteRequestBp\n)org.apache.skywalking.banyandb.measure.v1ZCgithub.com/apache/skywalking-banyandb/api/proto/banyandb/measure/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'banyandb.measure.v1.write_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n)org.apache.skywalking.banyandb.measure.v1ZCgithub.com/apache/skywalking-banyandb/api/proto/banyandb/measure/v1'
  _globals['_DATAPOINTVALUE'].fields_by_name['timestamp']._loaded_options = None
  _globals['_DATAPOINTVALUE'].fields_by_name['timestamp']._serialized_options = b'\372B\005\212\001\002\010\001'
  _globals['_DATAPOINTVALUE'].fields_by_name['tag_families']._loaded_options = None
  _globals['_DATAPOINTVALUE'].fields_by_name['tag_families']._serialized_options = b'\372B\005\222\001\002\010\001'
  _globals['_WRITEREQUEST'].fields_by_name['metadata']._loaded_options = None
  _globals['_WRITEREQUEST'].fields_by_name['metadata']._serialized_options = b'\372B\005\272\001\002\010\001'
  _globals['_WRITEREQUEST'].fields_by_name['data_point']._loaded_options = None
  _globals['_WRITEREQUEST'].fields_by_name['data_point']._serialized_options = b'\372B\005\272\001\002\010\001'
  _globals['_WRITEREQUEST'].fields_by_name['message_id']._loaded_options = None
  _globals['_WRITEREQUEST'].fields_by_name['message_id']._serialized_options = b'\372B\003\232\001\000'
  _globals['_WRITERESPONSE'].fields_by_name['message_id']._loaded_options = None
  _globals['_WRITERESPONSE'].fields_by_name['message_id']._serialized_options = b'\372B\003\232\001\000'
  _globals['_DATAPOINTVALUE']._serialized_start=180
  _globals['_DATAPOINTVALUE']._serialized_end=387
  _globals['_WRITEREQUEST']._serialized_start=390
  _globals['_WRITEREQUEST']._serialized_end=557
  _globals['_WRITERESPONSE']._serialized_start=559
  _globals['_WRITERESPONSE']._serialized_end=666
  _globals['_INTERNALWRITEREQUEST']._serialized_start=669
  _globals['_INTERNALWRITEREQUEST']._serialized_end=813
# @@protoc_insertion_point(module_scope)
