# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: publish-docker

on:
  pull_request:
  push:
    branches:
      - main

env:
  HUB: ghcr.io/apache
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 5

jobs:
  push-banyandb-image:
    if: github.repository == 'apache/skywalking-banyandb'
    runs-on: ${{ matrix.target }}-latest
    permissions:
      contents: read
      packages: write
    timeout-minutes: 90
    strategy:
      fail-fast: true
      matrix:
        target:
          - ubuntu
          - windows
    env:
      TAG: ${{ github.sha }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Cache Go Modules
        uses: actions/cache@v3
        id: cache-go
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Cache Tools
        uses: actions/cache@v3
        id: cache-tool
        with:
          path: bin
          key: ${{ runner.os }}-build-tool-${{ hashFiles('**version.mk') }}
          restore-keys: |
            ${{ runner.os }}-build-tool-
      - uses: actions/setup-node@v3
        with:
          node-version: 20.9
          cache: 'npm'
          cache-dependency-path: ui/package-lock.json
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: Update dependencies on Linux
        if: steps.cache-go.outputs.cache-hit != 'true' && matrix.target == 'ubuntu'
        run: GOPROXY=https://proxy.golang.org go mod download
      - name: Update dependencies on Windows
        if: steps.cache-go.outputs.cache-hit != 'true' && matrix.target == 'windows'
        run: |
          $env:GOPROXY="https://proxy.golang.org"
          go mod download
      - name: Generate codes
        run: make generate
      - name: Set up Docker Buildx on Linux
        if: matrix.target == 'ubuntu'
        uses: docker/setup-buildx-action@v1
      - name: Build binaries on Windows
        if: matrix.target == 'windows'
        run: |
          $env:BUILD_TAGS="prometheus"
          make -C banyand banyand-server-static
          make -C bydbctl build
      - name: Build docker image on Linux
        run: |
          make docker.build || make docker.build
          docker image ls
      - name: Log in to the Container registry
        uses: docker/login-action@v1.10.0
        if: github.ref == 'refs/heads/main'
        with:
          registry: ${{ env.HUB }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push docker image
        if: github.ref == 'refs/heads/main'
        run: |
          make docker.push || make docker.push